/**
 * Width steps generated by `npm run gen-screenshots`. Keep in sync with
 * TOP_WIDTH in that script: asking for a step it does not emit yields a 404.
 */
const STEPS: Record<ScreenshotAsset, number[]> = {
  dark: [960, 1920, 2560],
  light: [960, 1920, 2560],
  query: [960, 1920],
};

export type ScreenshotAsset = "dark" | "light" | "query";

export function screenshotSrcSet(asset: ScreenshotAsset, ext: "avif" | "webp"): string {
  return STEPS[asset].map((w) => `/screenshots/${asset}-${w}.${ext} ${w}w`).join(", ");
}

/** Largest step, used as the plain `src` fallback. */
export function screenshotFallback(asset: ScreenshotAsset): string {
  const widest = STEPS[asset][STEPS[asset].length - 1];
  return `/screenshots/${asset}-${widest}.webp`;
}
