// Generates src/lib/version.ts from the extension's root package.json so the
// landing site advertises the same version string as the published Chrome
// extension. Run automatically before `next build` and `next dev` via the
// "predev" / "prebuild" npm scripts; safe to run by hand any time.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const pkgPath = join(repoRoot, "package.json");
const outPath = resolve(here, "..", "src", "lib", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
if (typeof pkg.version !== "string") {
  console.error(`[sync-version] No version string in ${pkgPath}`);
  process.exit(1);
}

const banner = "// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n// Source of truth is the extension's root package.json.\n";
const body = `export const APP_VERSION = ${JSON.stringify(pkg.version)};\n`;
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${banner}\n${body}`, "utf8");
console.log(`[sync-version] wrote APP_VERSION=${pkg.version} to ${outPath}`);
